//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int Id_Serial { get; set; }
        public int Id_User { get; set; }
        public int Mark1 { get; set; }
    
        public virtual Serial Serial { get; set; }
        public virtual User User { get; set; }
    }
}
