//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    public partial class Serial : IDataErrorInfo
    {
        public Serial()
        {
            this.Marks = new ObservableCollection<Mark>();
            this.Series = new ObservableCollection<Series>();
            this.Genres = new ObservableCollection<Genre>();
            this.Users = new ObservableCollection<User>();
            this.Users1 = new ObservableCollection<User>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_TVChannel { get; set; }
        public string Description { get; set; }
        public Nullable<int> id_Status { get; set; }
        public string Path { get; set; }

        public string this[string columnName]
        {
            get
            {
                string error = String.Empty;
                switch (columnName)
                {
                    case "Name":
                        if (String.IsNullOrEmpty(Name))
                        {
                            error = "Serials name can't be empty";
                        }

                        break;
                }
                return error;
            }
        }
        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public virtual ICollection<Mark> Marks { get; set; }
        public virtual Status Status { get; set; }
        public virtual TVChannel TVChannel { get; set; }
        public virtual ICollection<Series> Series { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<User> Users1 { get; set; }


    }
}
