//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;

    public partial class Series : IDataErrorInfo
    {
        public Series()
        {
            this.Users = new ObservableCollection<User>();
        }

        public int Id { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public string this[string columnName]
        {
            get
            {
                string error = String.Empty;
                switch (columnName)
                {
                    case "Name":
                        if (String.IsNullOrEmpty(Name))
                        {
                            error = "Series name can't be empty";
                        }

                        break;
                    case "Number":
                        if (Number <= 0)
                        {
                            error = "Series number can't be zero or less";
                        }
                        break;
                    case "Season":
                        if (Season <= 0)
                        {
                            error = "Series season can't be zero or less";
                        }
                        break;

                }
                return error;
            }
        }
        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public int Id_Serial { get; set; }
        public short Season { get; set; }

        public virtual Serial Serial { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
